apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config

data:
  DATABASE_HOST: payment-db
  DATABASE_PORT: "5432"

  DJANGO_DEBUG: "False"
  DJANGO_SETTINGS_MODULE: config.settings

  ALLOWED_HOSTS: "localhost,127.0.0.1,auth-service,auth-db,gateway,catalog-service,inventory-service,order-service,payment-service,notification-service,.local"
