apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-db

  template:
    metadata:
      labels:
        app: payment-db

    spec:
      containers:
        - name: postgres

          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: payment-postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

      volumes:
        - name: payment-postgres-storage
          persistentVolumeClaim:
            claimName: payment-postgres-pvc