services:

  auth_db:
    image: postgres:16
    container_name: microshop-auth-db


    env_file:
      - ./services/auth-service/.env

    ports:
      - "5433:5432"

    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U auth_user -d auth_db"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service

    container_name: microshop-auth-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    env_file:
      - services/auth-service/.env

    ports:
      - "8000:8000"

    depends_on:
      auth_db:
        condition: service_healthy

  catalog_db:
    image: postgres:16
    container_name: microshop-catalog-db

    env_file:
      - services/catalog-service/.env

    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

    ports:
      - "5434:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U catalog_user -d catalog_db"
        ]

      interval: 5s
      timeout: 5s
      retries: 5

  catalog-service:
    build:
      context: ./services/catalog-service
    container_name: microshop-catalog-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    
    env_file:
      - services/catalog-service/.env

    ports:
      - "8001:8000"

    depends_on:
      catalog_db:
        condition: service_healthy

  inventory-db:
    image: postgres:16

    container_name: microshop-inventory-db

    env_file:
      - services/inventory-service/.env

    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

    ports:
      - "5435:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U inventory_user -d inventory_db"
        ]

      interval: 5s
      timeout: 5s
      retries: 5

  inventory-service:
    build:
      context: ./services/inventory-service

    container_name: microshop-inventory-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    env_file:
      - ./services/inventory-service/.env

    ports:
      - "8002:8000"

    depends_on:
      inventory-db:
          condition: service_healthy

  order-db:
    image: postgres:16
    container_name: microshop-order-db
    env_file:
      - services/order-service/.env
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./services/order-service
    container_name: microshop-order-service
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    env_file:
      - services/order-service/.env

    ports:
      - "8003:8000"

    depends_on:
      order-db:
        condition: service_healthy

      catalog-service:
        condition: service_started

  payment-db:
    image: postgres:16
    container_name: microshop-payment-db
    env_file:
      - services/payment-service/.env
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    healthcheck:
      test:
        [ "CMD-SHELL", "pg_isready -U payment_user -d payment_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_postgres_data:
  catalog_postgres_data:
  inventory_postgres_data:
  order_postgres_data:
  payment_postgres_data: