services:

  auth_db:
    image: postgres:16
    container_name: microshop-auth-db


    env_file:
      - ./services/auth-service/.env

    ports:
      - "5433:5432"

    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U auth_user -d auth_db"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service

    container_name: microshop-auth-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    env_file:
      - services/auth-service/.env

    ports:
      - "8000:8000"

    depends_on:
      auth_db:
        condition: service_healthy

  catalog_db:
    image: postgres:16
    container_name: microshop-catalog-db

    env_file:
      - services/catalog-service/.env

    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

    ports:
      - "5434:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U catalog_user -d catalog_db"
        ]

      interval: 5s
      timeout: 5s
      retries: 5

  catalog-service:
    build:
      context: ./services/catalog-service
    container_name: microshop-catalog-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    
    env_file:
      - services/catalog-service/.env

    ports:
      - "8001:8000"

    depends_on:
      catalog_db:
        condition: service_healthy

  inventory-db:
    image: postgres:16

    container_name: microshop-inventory-db

    env_file:
      - services/inventory-service/.env

    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

    ports:
      - "5435:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U inventory_user -d inventory_db"
        ]

      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  auth_postgres_data:
  catalog_postgres_data:
  inventory_postgres_data: