services:

  auth_db:
    image: postgres:16
    container_name: microshop-auth-db


    env_file:
      - ./services/auth-service/.env

    ports:
      - "5433:5432"

    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U auth_user -d auth_db"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service

    container_name: microshop-auth-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    env_file:
      - services/auth-service/.env

    ports:
      - "8000:8000"

    depends_on:
      auth_db:
        condition: service_healthy

  catalog_db:
    image: postgres:16
    container_name: microshop-catalog-db

    env_file:
      - services/catalog-service/.env

    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

    ports:
      - "5434:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U catalog_user -d catalog_db"
        ]

      interval: 5s
      timeout: 5s
      retries: 5

  catalog-service:
    build:
      context: ./services/catalog-service
    container_name: microshop-catalog-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    
    env_file:
      - services/catalog-service/.env

    ports:
      - "8001:8000"

    depends_on:
      catalog_db:
        condition: service_healthy

  inventory-db:
    image: postgres:16

    container_name: microshop-inventory-db

    env_file:
      - services/inventory-service/.env

    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

    ports:
      - "5435:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U inventory_user -d inventory_db"
        ]

      interval: 5s
      timeout: 5s
      retries: 5

  inventory-service:
    build:
      context: ./services/inventory-service

    container_name: microshop-inventory-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    env_file:
      - ./services/inventory-service/.env

    ports:
      - "8002:8000"

    depends_on:
      inventory-db:
          condition: service_healthy
      rabbitmq:
        condition: service_healthy

  order-db:
    image: postgres:16
    container_name: microshop-order-db
    env_file:
      - services/order-service/.env
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./services/order-service
    container_name: microshop-order-service
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    env_file:
      - services/order-service/.env

    ports:
      - "8003:8000"

    depends_on:
      order-db:
        condition: service_healthy

      catalog-service:
        condition: service_started

      rabbitmq:
        condition: service_healthy

  payment-db:
    image: postgres:16
    container_name: microshop-payment-db
    env_file:
      - services/payment-service/.env
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    healthcheck:
      test:
        [ "CMD-SHELL", "pg_isready -U payment_user -d payment_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service:
    build:
      context: ./services/payment-service
    container_name: microshop-payment-service
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    env_file:
      - services/payment-service/.env

    ports:
      - "8004:8000"

    depends_on:
      payment-db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

  notification-db:
    image: postgres:16
    container_name: microshop-notification-db

    env_file:
      - services/notification-service/.env

    volumes:
      - notification_postgres_data:/var/lib/postgresql/data

    ports:
      - "5438:5432"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U notification_user -d notification_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  notification-service:
    build:
      context: ./services/notification-service

    container_name: microshop-notification-service

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

    env_file:
      - services/notification-service/.env

    ports:
      - "8005:8000"

    depends_on:
      notification-db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: microshop-rabbitmq

    env_file:
      - .env

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  inventory-consumer:
    build:
      context: ./services/inventory-service

    container_name: microshop-inventory-consumer

    command:
      [
        "python",
        "manage.py",
        "consume_events"
      ]

    env_file:
      - services/inventory-service/.env

    depends_on:
      inventory-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  inventory-outbox:
    build:
      context: ./services/inventory-service

    container_name: microshop-inventory-outbox

    command: >
      sh -c "
      python manage.py publish_outbox
      "

    env_file:
      - services/inventory-service/.env

    depends_on:
      inventory-db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy


  order-consumer:
    build:
      context: ./services/order-service

    container_name: microshop-order-consumer

    command:
      [
        "python",
        "manage.py",
        "consume_events"
      ]

    env_file:
      - services/order-service/.env

    depends_on:
      order-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  order-outbox:
    build:
      context: ./services/order-service

    container_name: microshop-order-outbox

    command: >
      sh -c "
      python manage.py publish_outbox
      "

    env_file:
      - services/order-service/.env


    depends_on:
      order-db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

  payment-consumer:
    build:
      context: ./services/payment-service

    container_name: microshop-payment-consumer

    command:
      [
        "python",
        "manage.py",
        "consume_events"
      ]

    env_file:
      - services/payment-service/.env

    depends_on:
      payment-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  payment-outbox:
    build:
      context: ./services/payment-service

    container_name: microshop-payment-outbox

    command: >
      sh -c "
      python manage.py publish_outbox
      "

    env_file:
      - services/payment-service/.env

    depends_on:
      payment-db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy


  notification-consumer:
    build:
      context: ./services/notification-service

    container_name: microshop-notification-consumer

    command:
      [
        "python",
        "manage.py",
        "consume_events"
      ]

    env_file:
      - services/notification-service/.env

    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: microshop-redis

    command:
      [
        "redis-server",
        "--appendonly",
        "yes"
      ]

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  notification-worker:
    build:
      context: ./services/notification-service

    container_name: microshop-notification-worker

    command:
      [
        "celery",
        "-A",
        "config",
        "worker",
        "--loglevel=INFO",
        "--concurrency=2"
      ]

    env_file:
      - services/notification-service/.env

    depends_on:

      notification-db:
        condition: service_healthy

      redis:
        condition: service_healthy


  notification-beat:
    build:
      context: ./services/notification-service

    container_name: microshop-notification-beat

    command:
      [
        "celery",
        "-A",
        "config",
        "beat",
        "--loglevel=INFO"
      ]

    env_file:
      - services/notification-service/.env

    depends_on:

      notification-db:
        condition: service_healthy

      redis:
        condition: service_healthy

volumes:
  auth_postgres_data:
  catalog_postgres_data:
  inventory_postgres_data:
  order_postgres_data:
  payment_postgres_data:
  notification_postgres_data:
  rabbitmq_data:
  redis_data: