apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: microshop-notification-service:1.0.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: DATABASE_PORT

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: POSTGRES_DB

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: POSTGRES_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: POSTGRES_PASSWORD

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-app-secret
                  key: SECRET_KEY

            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: ALLOWED_HOSTS

            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: DJANGO_SETTINGS_MODULE

          command:
            - sh
            - -c

          args:
            - |
              echo "Waiting for notification-db..."

              until python -c "
              import socket
              socket.create_connection(('notification-db', 5432), timeout=2)
              "; do
                echo "notification-db is not ready yet..."
                sleep 2
              done

              echo "notification-db is reachable."

              python manage.py migrate && \
              exec gunicorn config.wsgi:application \
                --bind 0.0.0.0:8000 \
                --workers 3

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: notification-service

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: notification-service

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5